import os
import json
import logging
from openai import AsyncOpenAI
from backend.models.explanation import ExplanationRequest, AIExplanation

logger = logging.getLogger(__name__)

SYSTEM_PROMPT = """You are the explanation layer of Wealthsimple Pulse, an AI-powered monthly financial decision engine.

CRITICAL BOUNDARIES — violating any of these is a system failure:
1. All numbers, projections, scores, and deltas you receive are PRE-COMPUTED by the deterministic engine. You must NEVER recalculate, adjust, round differently, or invent any number.
2. You INTERPRET and EXPLAIN results. You do not provide financial advice or personal recommendations.
3. Frame everything as analysis of computed outputs. Use phrases like "the analysis shows" or "based on the projections."
4. Never use language implying guaranteed outcomes. Markets are uncertain; projections are estimates.
5. Never suggest actions beyond what the engine has scored. Do not invent alternative actions.

BANNED PHRASES — never use any of these:
"I think", "I believe", "you should", "I recommend", "it's important to note", "it goes without saying", "in conclusion", "needless to say", "as an AI", "certainly", "absolutely"

PERSONALIZATION RULES:
- If a user name is provided, address them by first name ONCE in the opening of the narrative (e.g., "Sarah, the analysis shows..."). Do not repeat the name elsewhere.
- If a goal purpose is provided (e.g., "home", "retirement"), reference it naturally when discussing projections (e.g., "your home purchase goal" instead of "your goal"). Use it at most twice.
- If a financial concern is provided, acknowledge it in ONE risk warning if the data supports it. Do not force it.
- If a personal note is provided, incorporate its context only if directly relevant to the computed data.
- Do not over-personalize. Every statement must be grounded in the computed numbers.

YOUR TASK:
Given a user's pre-computed financial snapshot, scenario analysis, and ranked actions, produce a JSON object with these exact fields:

{
  "narrative": "<3-4 sentences, under 120 words. Summarize the user's financial position and why the top action is the highest-leverage move. Reference specific numbers from the data. Start with the user's name if provided.>",
  "reasoning": "<Exactly 2 sentences. Explain which deltas drove the top action's score and how the risk profile influenced the weights.>",
  "alternatives_analysis": "<Exactly 2 sentences. Why the #2 and #3 ranked actions scored lower. Reference their specific deltas.>",
  "risk_warnings": ["<2-3 items. Each is exactly 1 sentence. Reference scenario results, liquidity gaps, or allocation mismatches. If a financial concern was stated, address it in one warning.>"],
  "confidence_score": <Float 0-1. Use the provided score_gap: gap > 0.3 = 0.85+, gap 0.1-0.3 = 0.6-0.85, gap < 0.1 = 0.4-0.6.>,
  "disclaimer": "This analysis is generated by AI interpreting pre-computed deterministic projections. It does not constitute financial advice. All projections are estimates based on historical return assumptions. Consult a qualified financial advisor before making investment decisions."
}

EXAMPLE OUTPUT (for reference — adapt tone, not content):
{
  "narrative": "Sarah, the analysis shows your savings rate of 41.7% and 6.3 months of emergency coverage provide a strong foundation toward your home purchase goal. Under base conditions, the projected portfolio value reaches $632,000 against your $500,000 target, yielding a 100.0% goal probability. Increasing your equity allocation by 10% is the highest-leverage move, improving goal delta by +2.8% while keeping risk within your medium-tolerance band.",
  "reasoning": "The top action scored 0.72 primarily driven by a +2.8% goal delta, which carries 35% weight under the medium risk profile. The liquidity and risk deltas were neutral, meaning the score was concentrated in goal acceleration.",
  "alternatives_analysis": "Increasing monthly contribution by 10% scored 0.68 with a comparable goal delta of +2.5% but added no risk reduction. Building the emergency fund to 6 months scored 0.61 — its +1.2 month liquidity gain was offset by a 0.0% goal delta.",
  "risk_warnings": ["Under recession conditions, goal probability drops to 80.9%, a 19.1 percentage point decline from the base case.", "Your equity allocation of 70% after this action would exceed the recommended 55% for medium-risk investors by 15 percentage points.", "Market volatility could significantly impact near-term portfolio value, particularly relevant given your stated concern about market conditions."],
  "confidence_score": 0.72,
  "disclaimer": "This analysis is generated by AI interpreting pre-computed deterministic projections. It does not constitute financial advice. All projections are estimates based on historical return assumptions. Consult a qualified financial advisor before making investment decisions."
}

STYLE RULES:
- Plain language, no jargon. Write for a retail investor, not a finance professional.
- Professional but warm tone. Be honest about uncertainty.
- Be specific: reference actual numbers, percentages, and scenario outcomes.
- Keep each field within its specified length. Do not exceed limits.
- The disclaimer field must always contain the exact text shown above.
- Every sentence must contain at least one specific number from the provided data."""

GUARDRAILS = [
    "AI does not perform calculations — all numbers are pre-computed by deterministic engine",
    "AI cannot execute trades or modify user accounts",
    "AI output is interpretation only, not financial advice",
    "Confidence score is bounded by deterministic score gap",
    "Disclaimer is enforced on every response",
]

GOAL_PURPOSE_LABELS = {
    "home": "home purchase",
    "retirement": "retirement",
    "education": "education",
    "travel": "travel",
    "emergency": "emergency fund",
    "general_wealth": "wealth building",
}

CONCERN_LABELS = {
    "market_volatility": "market volatility",
    "not_saving_enough": "not saving enough",
    "debt": "debt levels",
    "inflation": "inflation",
    "retirement_readiness": "retirement readiness",
}


def _compute_score_gap(request: ExplanationRequest) -> float:
    """Deterministic confidence proxy based on gap between #1 and #2 ranked actions."""
    actions = request.ranked_actions
    if len(actions) < 2:
        return 1.0
    return round(actions[0].total_score - actions[1].total_score, 4)


def _build_user_message(request: ExplanationRequest) -> str:
    """Serialize the deterministic engine output and personal context into a structured block for the LLM."""
    snap = request.financial_snapshot
    top = request.top_recommendation
    actions = request.ranked_actions
    score_gap = _compute_score_gap(request)

    context_lines = []
    if request.first_name:
        context_lines.append(f"  Name: {request.first_name}")
    if request.age:
        context_lines.append(f"  Age: {request.age}")
    if request.life_stage:
        context_lines.append(f"  Life stage: {request.life_stage.replace('_', ' ').title()}")
    if request.goal_purpose:
        label = GOAL_PURPOSE_LABELS.get(request.goal_purpose, request.goal_purpose)
        context_lines.append(f"  Goal: Saving for {label}")
    if request.financial_concern and request.financial_concern != "none":
        label = CONCERN_LABELS.get(request.financial_concern, request.financial_concern)
        context_lines.append(f"  Top concern: {label}")
    if request.personal_note:
        context_lines.append(f'  Note: "{request.personal_note}"')

    context_block = ""
    if context_lines:
        context_block = "USER CONTEXT:\n" + "\n".join(context_lines) + "\n\n"

    scenarios_text = "\n".join(
        f"  - {s.label}: annual return {s.annual_return:.2%}, "
        f"projected value ${s.projected_value:,.0f}, "
        f"goal probability {s.goal_probability:.1%}"
        for s in snap.scenarios
    )

    actions_text = "\n".join(
        f"  #{i+1} [{a.total_score:.2f}] {a.name}\n"
        f"      Goal \u0394: {a.goal_delta:+.2%} | Liquidity \u0394: {a.liquidity_delta:+.2f}mo | Risk \u0394: {a.risk_delta:+.2%}\n"
        f"      {a.rationale}"
        for i, a in enumerate(actions)
    )

    insights_text = "\n".join(f"  - {ins}" for ins in snap.insights)

    return f"""{context_block}USER RISK PROFILE: {request.risk_profile}

FINANCIAL SNAPSHOT (pre-computed):
  Savings rate: {snap.savings_rate:.1%}
  Monthly surplus: ${snap.monthly_surplus:,.0f}
  Liquidity: {snap.liquidity_ratio:.1f} months of expenses
  Projected base return: {snap.projected_base_return:.2%}
  Risk exposure score: {snap.risk_exposure_score:.2%}
  Goal funding gap: ${snap.goal_funding_gap:,.0f}
  Goal probability (base): {snap.estimated_goal_probability:.1%}

SCENARIO ANALYSIS (pre-computed):
{scenarios_text}

ENGINE INSIGHTS:
{insights_text}

RANKED ACTIONS (pre-scored, descending):
{actions_text}

TOP RECOMMENDATION:
  Action: {top.action}
  Impact: {top.impact_summary}
  Tradeoff: {top.tradeoff}

SCORE GAP (top vs #2): {score_gap:.4f}
Use this to calibrate confidence_score: gap > 0.3 \u2192 0.85+, gap 0.1\u20130.3 \u2192 0.6\u20130.85, gap < 0.1 \u2192 0.4\u20130.6.

Respond with a single JSON object matching the schema described in your instructions. No markdown, no code fences, just raw JSON."""


async def generate_explanation(
    request: ExplanationRequest,
) -> AIExplanation:
    """Call the LLM to interpret the deterministic engine output.

    Uses structured prompting with strict boundaries, personalization rules,
    and few-shot examples for consistent output.
    """
    api_key = os.getenv("OPENAI_API_KEY")
    if not api_key:
        raise EnvironmentError("OPENAI_API_KEY not set")

    model = os.getenv("LLM_MODEL", "gpt-4o-mini")
    client = AsyncOpenAI(api_key=api_key)

    try:
        response = await client.chat.completions.create(
            model=model,
            temperature=0.15,
            max_tokens=800,
            response_format={"type": "json_object"},
            messages=[
                {"role": "system", "content": SYSTEM_PROMPT},
                {"role": "user", "content": _build_user_message(request)},
            ],
        )

        raw = response.choices[0].message.content
        parsed = json.loads(raw)

        score_gap = _compute_score_gap(request)
        parsed["confidence_score"] = _clamp_confidence(
            parsed.get("confidence_score", 0.5), score_gap
        )

        parsed["disclaimer"] = (
            "This analysis is generated by AI interpreting pre-computed deterministic "
            "projections. It does not constitute financial advice. All projections are "
            "estimates based on historical return assumptions. Consult a qualified "
            "financial advisor before making investment decisions."
        )

        return AIExplanation(**parsed)

    except json.JSONDecodeError:
        logger.exception("LLM returned invalid JSON")
        raise ValueError("AI explanation could not be parsed")
    except Exception:
        logger.exception("LLM call failed")
        raise


def _clamp_confidence(llm_value: float, score_gap: float) -> float:
    """Override LLM's confidence with deterministic bounds so it can't hallucinate certainty."""
    if score_gap > 0.3:
        return max(min(llm_value, 1.0), 0.85)
    elif score_gap > 0.1:
        return max(min(llm_value, 0.85), 0.6)
    else:
        return max(min(llm_value, 0.6), 0.4)


def get_model_name() -> str:
    return os.getenv("LLM_MODEL", "gpt-4o-mini")
